// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/density-demo
// buildId: 7d8bb67bcc5beef8859cf82b33c794060d8194b509264c6570ab4ab974ef5ae3
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const densityDemoStyles = Object.freeze({
  "row": "x78zum5 x1a02dak xiouwu1",
  "cell": "x845mor xpqbu8w",
  "label": "x1lliihq xzavzzj x1ogzq0l xa69gwt x1o79442 xtvhhri xowzrx4",
  "scopeBox": "x1j5qm77 x1y0btm7 xwcd3x7 x1pr2me3",
});
