// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/density-demo
// buildId: b3ad961302de84899611d87ca5d0c5c564f205140fe2b2a2409e6feb8bf37b44
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const densityDemoStyles = Object.freeze({
  "row": "x78zum5 x1a02dak xiouwu1",
  "cell": "x845mor xpqbu8w",
  "label": "x1lliihq xzavzzj x1ogzq0l xa69gwt x1o79442 xtvhhri xowzrx4",
  "scopeBox": "x1j5qm77 x1y0btm7 xwcd3x7 x1pr2me3",
});
