// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/density-demo
// buildId: 654954299e69627125bd42b76c4c97064da9f26b80ed6b67cbb2832feb1baf07
// generator: @jixoai/ui-vite-plugin@0.6.0
// engine: @stylexjs/unplugin@0.19.0
export const densityDemoStyles = Object.freeze({
  "row": "x78zum5 x1a02dak xiouwu1",
  "cell": "xwb5pt4 xpqbu8w",
  "label": "x1lliihq xzavzzj x1ogzq0l xa69gwt x1o79442 xtvhhri xowzrx4",
  "scopeBox": "x1j5qm77 x1y0btm7 xwcd3x7 x1pr2me3 xw2csxc",
});
