// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: scroll-area
// buildId: 7d8bb67bcc5beef8859cf82b33c794060d8194b509264c6570ab4ab974ef5ae3
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const scrollAreaStyles = Object.freeze({
  "region": "x1n2onr6",
  "viewport": "xish69e",
  "viewportVertical": "x6ikm8r x1odjw0f",
  "viewportHorizontal": "xw2csxc x10wlt62",
  "viewportBoth": "xw2csxc x1odjw0f",
  "content": "x5yr21d",
});
