// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/props-table
// buildId: 7119ccca8c08e569354ee25ccf3745534e92764eb2e7a0f2f9be5fa80bc54567
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const propsTableStyles = Object.freeze({
  "scroller": "xh8yej3 xw2csxc",
  "title": "xzavzzj x1ogzq0l xxguibh",
  "table": "xh8yej3 x1mwwwfo x1yc453h",
  "headRow": "x1u25o6y x1q0q8m5 xwi7vqo",
  "bodyRow": "x1u25o6y x1q0q8m5 xwcd3x7",
  "headCell": "xzavzzj xbmwfkb xwwigjq xa69gwt xtvhhri xp0kdp7",
  "nameCell": "xbmwfkb xwwigjq x1mwizrc xxguibh xuxw1ft",
  "typeCell": "xbmwfkb xwwigjq x1mwizrc xa69gwt xowzrx4",
  "defaultCell": "xbmwfkb xwwigjq x1mwizrc xa69gwt xowzrx4",
  "descriptionCell": "xbmwfkb xwwigjq xxguibh",
  "required": "x18as732",
  "bindChip": "xowzrx4 x1o1qgpq x1lacwl7",
});
