// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/separator
// buildId: 10eaa095ab1529669335f17d32334f85db0e3dba504ea36826a8c22973f00253
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const separatorStyles = Object.freeze({
  "horizontal": "xh8yej3 xjm9jq1 x1s3qnfn xbzouxq xc342km xng3xce",
  "vertical": "x1i1rx1s xkh2ocl x1okw0bk x1s3qnfn xbzouxq",
  "solidHorizontal": "x1t853zo xnf7tsy",
  "solidVertical": "x1t853zo xnf7tsy",
  "dashedH": "x1ycxmf xxg92ui",
  "dashedV": "x130xnox x1mauu7a",
  "denseH": "xdm3r4a x1n3fem5",
  "denseV": "x3q4nmu x1fb04h1",
  "dottedH": "x36qwtl xzw1ypj x5cpf72 xsbdu3q x1pf8epq x1wsrsg2 x1wix2xn",
  "dottedV": "xfo62xy xzw1ypj x5cpf72 xhxtcz0 x1a1638o xcljghj xi0he60",
  "wavyH": "xols6we x1uv594n x1is8714 x3d3ze xrqyqz2 x1wsrsg2 x1wix2xn",
  "wavyV": "x1v4s8kt xwrgzkm x1tmcpx8 x1j3x0ap x8x7f8w xcljghj xi0he60",
  "fadeH": "x1t853zo x1go0ci8 x6176g0",
  "fadeV": "x1t853zo xm93v8h x6176g0",
});
