// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: scroll-virtual
// buildId: 5aad4b01f9f2defbbd38278058b3b1d716b47c915721252c1b34ae2218f2c0af
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const scrollVirtualStyles = Object.freeze({
  "spacer": "x1n2onr6",
});
