// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/popover
// buildId: 10eaa095ab1529669335f17d32334f85db0e3dba504ea36826a8c22973f00253
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const popoverStyles = Object.freeze({
  "anchor": "x3nfvp2",
  "trigger": "x3nfvp2 x1ypdohk x6s0dn4 xb6y1gh xmkeg23 x1y0btm7 xwi7vqo x1rnfs7p x13s4r1c x13eudtd xc68ue2 xkpwil5 xk50ysn xl8unsv xj0zi7g xnroaok x1fxrjlo x1ll51s2 xym9jgt x1i1q1sf x1xtu34k x7s97pk x9kvfbb",
  "caret": "x3nfvp2 x1okw0bk x11xpdln xx6bhzk x9lcvmn",
  "shadow": "x10l6tqk x10a8y8t x8knxv4 x1uhehlj x12x07u7 x1495lsp x1l1uqgk",
  "body": "x1n2onr6 xmkeg23 x1y0btm7 xwi7vqo xfmjrly",
  "bodyAcrylic": "xe6n8c8 xni0bam x19bkbe6 x1t4lvf3 x11rvarm x1pe93vg",
  "scroll": "x1nphckf xysyzu8 xliy32w xbnopvp x2k91m2",
});
