// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/icon
// buildId: e12c98c6feb373f1861e907a966420d7969018bd07cbc08ac11a31858f99eeac
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const iconStyles = Object.freeze({
  "reserved": "x1rg5ohu",
  "reservedSize": "xkd2l6g x17uqirv",
});
