// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/icon
// buildId: 60807e498baf091b1e47652e09051c40fe6817a687a7e2b1e63402a96062740f
// generator: @jixoai/ui-vite-plugin@0.3.0
// engine: @stylexjs/unplugin@0.19.0
export const iconStyles = Object.freeze({
  "reserved": "x1rg5ohu",
  "reservedSize": "xkd2l6g x17uqirv",
});
