// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/icon
// buildId: d2f8f1efd193cdbf3ee9e9e340a002ffaaf0f5071638076c2f0d3a165f5e94d4
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const iconStyles = Object.freeze({
  "reserved": "x1rg5ohu",
  "reservedSize": "xkd2l6g x17uqirv",
});
