// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: list-item
// buildId: 654954299e69627125bd42b76c4c97064da9f26b80ed6b67cbb2832feb1baf07
// generator: @jixoai/ui-vite-plugin@0.6.0
// engine: @stylexjs/unplugin@0.19.0
export const itemStyles = Object.freeze({
  "divider": "x3ct3a4 x1ghz6dp x1717udv",
});
