// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/a11y-table
// buildId: 7119ccca8c08e569354ee25ccf3745534e92764eb2e7a0f2f9be5fa80bc54567
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const a11yTableStyles = Object.freeze({
  "root": "x78zum5 xdt5ytf xiouwu1",
  "heading": "xzavzzj x1ogzq0l xxguibh",
  "table": "xh8yej3 x1mwwwfo xdpxx8g",
  "headRow": "x15nk5b1 x1q0q8m5 x1g6nami",
  "headCell": "xzavzzj xbmwfkb xwwigjq xa69gwt xtvhhri x67e80a",
  "bodyRow": "x15nk5b1 x1q0q8m5 x1isn79j",
  "cell": "xbmwfkb xwwigjq xxguibh",
  "cellMono": "xbmwfkb xwwigjq x1mwizrc xxguibh",
  "cellMonoSecondary": "xbmwfkb xwwigjq x1mwizrc xa69gwt xowzrx4",
  "kbd": "x1j5qm77 x1y0btm7 xwi7vqo x1yn5p49 x12003e7 x1vmuup6 x1mwizrc xxguibh",
});
