// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: website-scaffold
// buildId: 0ce7cb9fd93bfb6d0c326c10126a270111182c0d8894fc9ce51d327ff7ca2ee0
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const scaffoldStyles = Object.freeze({
  "main": "x845mor",
});
