/**
 * Geometry consistency gate (C4, ui-plugin-followup; migrated to
 * vite-plugin/icons with merge-alignment A1).
 *
 * Verifies the lucide single-source law: the provider's serialized
 * output must equal the `lucide` package's own IconNode children, and
 * the component lib (registry/files/lib/icons.ts) must embed the same
 * geometry. Both sides are DERIVED from `lucide` — no hand-copied
 * path literals in this file.
 *
 * registry/files/lib/icons.ts is regenerated by a separate batch, so
 * its svg bodies are compared only when the named exports parse
 * cleanly, and per-attribute (order-tolerant on both element order
 * and attribute order; the geometry itself must still match).
 */
import { Calendar, Check, ChevronDown, Clock, Palette, X } from 'lucide';
import type { IconNode, IconNodeChild } from 'lucide';
import { describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { lucideIconProvider } from '../../src/icons/providers/lucide.js';
import type { IconSlot } from '../../src/icons/types.js';

const here = resolve(fileURLToPath(import.meta.url), '..');
// test/icons → four levels up is the repo root
const repoRoot = resolve(here, '../../../..');

/** the provider's wrapper — byte-pinned; strip it to get the children */
const WRAPPER_OPEN =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">';

/** slots shared between the provider and registry/files/lib/icons.ts */
const SHARED_SLOTS: readonly { slot: IconSlot; icon: IconNode; exportName: string }[] = [
  { slot: 'calendar', icon: Calendar, exportName: 'calendar' },
  { slot: 'clock', icon: Clock, exportName: 'clock' },
  { slot: 'chevron', icon: ChevronDown, exportName: 'chevronDown' },
  { slot: 'palette', icon: Palette, exportName: 'palette' },
  { slot: 'check', icon: Check, exportName: 'check' },
  { slot: 'clear', icon: X, exportName: 'x' },
];

/** the provider's inner-SVG grammar: attrs in insertion order, self-closing, no separators */
function serializeChildren(children: readonly IconNodeChild[] | undefined): string {
  return (children ?? [])
    .map(([tag, attrs]) => {
      const attributes = Object.entries(attrs)
        .map(([name, value]) => ` ${name}="${value}"`)
        .join('');
      return `<${tag}${attributes}/>`;
    })
    .join('');
}

function makeContext() {
  return { ctx: { loadSource: vi.fn(), watchFile: vi.fn() } };
}

/** extract an `export const <name> = svg('...')` body from icons.ts, or null when absent/unparseable */
function registryExportBody(src: string, name: string): string | null {
  const match = new RegExp(
    `export\\s+const\\s+${name}\\s*=\\s*svg\\(\\s*(['"])((?:(?!\\1).)*)\\1`,
    's',
  ).exec(src);
  return match ? match[2]! : null;
}

describe('geometry consistency gate (C4)', () => {
  it('provider output equals lucide IconNode children for every shared slot', async () => {
    const { ctx } = makeContext();
    const provider = await lucideIconProvider()(ctx);
    for (const { slot, icon } of SHARED_SLOTS) {
      const svg = provider.getIcon(slot)!.svg;
      expect(svg.startsWith(WRAPPER_OPEN), `${slot} wrapper`).toBe(true);
      expect(svg.endsWith('</svg>'), `${slot} wrapper`).toBe(true);
      const children = svg.slice(WRAPPER_OPEN.length, -'</svg>'.length);
      expect(children, slot).toBe(serializeChildren(icon[2]));
    }
  });

  // Skipped when the registry file is mid-regeneration (exports don't
  // parse); a clean parse must carry the full geometry or this fails.
  const iconsSrc = readFileSync(resolve(repoRoot, 'registry/files/lib/icons.ts'), 'utf8');
  const registryBodies = new Map(SHARED_SLOTS.map(({ slot, exportName }) => [
    slot,
    registryExportBody(iconsSrc, exportName),
  ] as const));
  const registryParses = [...registryBodies.values()].every((body) => body !== null);

  it.skipIf(!registryParses)('registry icons.ts embeds the same lucide geometry', () => {
    for (const { slot, icon } of SHARED_SLOTS) {
      const body = registryBodies.get(slot)!;
      for (const [tag, attrs] of icon[2] ?? []) {
        expect(body, `${slot} <${tag}> element`).toContain(`<${tag}`);
        for (const [name, value] of Object.entries(attrs)) {
          expect(body, `${slot} <${tag} ${name}>`).toContain(`${name}="${value}"`);
        }
      }
    }
  });

  it('viewBox is 0 0 24 24 across sources', async () => {
    const { ctx } = makeContext();
    const provider = await lucideIconProvider()(ctx);
    expect(provider.getIcon('chevron')!.svg).toContain('viewBox="0 0 24 24"');
    expect(iconsSrc).toContain('viewBox="0 0 24 24"');
  });
});
