// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/token-table
// buildId: f6558fb12906568c70cc330f4e3cb1a3cd4765df5da5bf5a7ace526ad3b96eed
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const tokenTableStyles = Object.freeze({
  "scroller": "xh8yej3 xw2csxc",
  "table": "xh8yej3 x1mwwwfo x1yc453h",
  "headRow": "x1u25o6y x1q0q8m5 xwi7vqo",
  "bodyRow": "x1u25o6y x1q0q8m5 xwcd3x7",
  "headCell": "xzavzzj xbmwfkb xwwigjq xa69gwt xtvhhri xp0kdp7",
  "nameCell": "xbmwfkb xwwigjq x1mwizrc xxguibh xuxw1ft",
  "defaultCell": "xbmwfkb xwwigjq x1mwizrc xxguibh xowzrx4",
  "sourceCell": "xbmwfkb xwwigjq xa69gwt xowzrx4",
});
