/**
 * The component-structure IR (canvas-schema-pipeline, 2026-08-30).
 *
 * Zero-dependency plain objects, jsonSchema-shaped with `x-ui`
 * annotations. The IR is what the store holds, what the panel consumes
 * and what exports verbatim (via lower.ts) — "导出即消费，承诺可审计".
 * zod is NOT a dependency: third parties lower `z.toJSONSchema()` output
 * into the same front door (toJSONSchema accepts anything structurally
 * compatible with ComponentMeta).
 *
 * Internal vocabulary (`kind`, `typeText`) lives ONLY here; lower.ts
 * guarantees it never reaches an export.
 */

import type { UniversalAxisDoc } from '../universal-props.schema';

/**
 * Control hints the panel understands; `'none'` excludes the row.
 *
 * The explicit-props additions (W4 4.1, design §17 — FROZEN text):
 * `'axis-enum'` (the named/auto lane of a universal axis — the enum
 * select carrying the axis' namedSteps plus the `number`/`query()`
 * mode steps), `'axis-number'` (the axis' exact-number lane — the
 * spinner; unit per axis), `'query-editor'` (the query() source
 * editor). Feasibility + row synthesis live in the canvas kernel's
 * controlsFor; the lowering marks axis props with them from
 * meta.universal (lower.ts's axis-aware path).
 */
export type ControlHint =
  | 'segmented'
  | 'select'
  | 'toggle'
  | 'stepper'
  | 'slider'
  | 'text'
  | 'none'
  | 'axis-enum'
  | 'axis-number'
  | 'query-editor';

/**
 * Panel-facing annotation vocabulary. Carried verbatim into exports
 * under the `x-ui` keyword. `sourceType` is written by the lowering for
 * snippet/opaque nodes (their honest source type text, documented but
 * panel-excluded) — it is descriptive, never internal vocabulary.
 */
export interface XUI {
  control?: ControlHint;
  label?: string;
  description?: string;
  lane?: 'end' | 'block';
  unit?: string;
  /** source type text for snippet/opaque nodes (lowering output only) */
  sourceType?: string;
  /**
   * The axis an axis-control row serves (explicit-props W4): written
   * by the lowering when meta.universal marks the prop as a universal
   * axis lane — the kernel synthesizes the `:number`/`:query` sibling
   * rows and the dock gates their visibility on the axis' mode.
   */
  axis?: string;
}

/** A representable enum: string literal unions. */
export interface IREnumNode {
  kind: 'enum';
  values: string[];
  default?: string;
}
export interface IRStringNode {
  kind: 'string';
  default?: string;
}
export interface IRBooleanNode {
  kind: 'boolean';
  default?: boolean;
}
export interface IRNumberNode {
  kind: 'number';
  minimum?: number;
  maximum?: number;
  multipleOf?: number;
  default?: number;
}
/** Snippet props: documented with their source type text, panel-excluded. */
export interface IRSnippetNode {
  kind: 'snippet';
  typeText: string;
}
/** Imported/unresolved types: the honest ceiling, never silently dropped. */
export interface IROpaqueNode {
  kind: 'opaque';
  typeText: string;
}

export type IRNode =
  | IREnumNode
  | IRStringNode
  | IRBooleanNode
  | IRNumberNode
  | IRSnippetNode
  | IROpaqueNode;

/**
 * The defaults-contract ambient state (context-defaults-economy 4.3):
 * how a slot-carrying prop's effective default resolves when the caller
 * is silent — 'zone' (paint axis: providePaintZone ancestry), 'scope'
 * (density axis: the ambient css scope channel), 'own' (literal family:
 * a declared own, never ambient). The three spellings are the frozen
 * docs vocabulary (design r11 #4). A prop without a Defaults slot
 * carries no field. Docs-facing: from-meta reads it, lower.ts never
 * exports it. Written by component-metadata-gen from the family's
 * *-defaults.svelte.ts slot facts (drift-gated by --check).
 */
export type AmbientKind = 'zone' | 'scope' | 'own';

/** One prop: an IR node plus optional hand-authored `x-ui` hints. */
export type PropNode = IRNode & { 'x-ui'?: XUI; ambient?: AmbientKind };

/** The component meta a `.meta.ts` file exports. */
export interface ComponentMeta {
  /** registry source path the metadata was extracted from */
  source: string;
  props: Record<string, PropNode>;
  /** `data-jx-*` hook attribute names found in the template */
  hooks: readonly string[];
  /**
   * The universal-props block (explicit-props §17, W1 1.9): the
   * eight-axis doc table, GENERATED by component-metadata-gen's merge
   * step (universal === UNIVERSAL_AXES) — never hand-copied. OPTIONAL
   * at the type level; the drift gate enforces PRESENCE for every
   * non-exempt family (exempt metas legally omit it, Codex r7 B4).
   */
  universal?: readonly UniversalAxisDoc[];
}

/** Hand-authored zone shape: `x-ui` hints keyed by prop name. */
export interface PropAnnotation {
  'x-ui'?: XUI;
}
export interface Annotations {
  [prop: string]: PropAnnotation;
}

/** Identity-typed helper — the GENERATED zone's entry point. */
export function defineComponentMeta(meta: ComponentMeta): ComponentMeta {
  return meta;
}

/** Identity-typed helper — the hand-authored annotations zone. */
export function defineAnnotations(annotations: Annotations): Annotations {
  return annotations;
}

/**
 * Consume-time merge of hand annotations into a meta. Annotation keys
 * outside `props` are a TYPE ERROR at consume time (the mapped `never`
 * arm). Per-field, the annotation wins over the node's own `x-ui`.
 */
export function withAnnotations<
  M extends ComponentMeta,
  A extends Annotations,
>(meta: M, annotations: A & { [K in keyof A]: K extends keyof M['props'] ? PropAnnotation : never }): ComponentMeta {
  const props: Record<string, PropNode> = {};
  for (const [key, node] of Object.entries(meta.props)) {
    const hint = annotations[key]?.['x-ui'];
    props[key] = hint
      ? { ...node, 'x-ui': { ...node['x-ui'], ...hint } }
      : node;
  }
  return { ...meta, props };
}
