/**
 * wiring.test.ts — the stylex feature's build contracts (stylex-kernel
 * phase 0 P0.2; the plugin.test.ts fixture pattern):
 *
 *   1. THE F9 LAYER LAW: an emitted css asset that carries stylex
 *      output STARTS with the canonical FULL statement at byte zero —
 *      ahead of any other css (the O1-H remedy position; the
 *      statement text itself is pinned to the F9 ruling verbatim).
 *   2. the engine output really rides the asset (defineVars vars +
 *      @layer components.stylex.priorityN blocks, nested under
 *      components — the Gate-2 P1-1 general law) — the positive
 *      end-to-end path through vite build + the bridge.
 *   3. THE CSS-ENTRY TRAP (spike-report §5.2): a build with stylex
 *      output but NO css asset writes the fallback assets/stylex.css
 *      (statement-first) instead of losing the css silently.
 *   4. THE KERNEL-SCOPE GATE, unit-driven at the engine surface: an
 *      out-of-scope id NEVER reaches the babel transform (null before
 *      the engine), an in-scope id does — the law "kernel trees ONLY".
 */

import { mkdir, mkdtemp, readFile, readdir, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { beforeEach, describe, expect, it } from 'vitest';
import { build } from 'vite';

import { jixoai, canonicalLayerStatement, maxStylexPriority, parseCanonicalStatement } from '../../src/index.ts';
import { createStylexEngine } from '../../src/stylex/vite-plugin.ts';

const packageRoot = join(fileURLToPath(new URL('../..', import.meta.url)));

// the F9 ruling, verbatim — the test pins the STATEMENT BUILDER against
// the ruling text so the generated bytes can never drift silently
// (Gate-2 P1-1: dynamic over the css's highest tier, tiers nested under
// `components`, utilities constantly last)
const F9_CANONICAL_N3 =
  '@layer properties, theme, base, components, components.stylex.priority1, components.stylex.priority2, components.stylex.priority3, utilities;';
const F9_CANONICAL_SHEET = '@layer properties, theme, base, components, utilities;';

let outRoot: string;
let fixtureRoot: string;

beforeEach(async () => {
  outRoot = await mkdtemp(join(tmpdir(), 'jixoai-stylex-'));
  fixtureRoot = join(outRoot, 'fixture');
});

async function writeKernelFixture(withCssEntry: boolean, entryCss = 'body { margin: 0; }\n'): Promise<void> {
  await mkdir(join(fixtureRoot, 'src', 'kernel'), { recursive: true });
  await mkdir(join(fixtureRoot, 'src', 'docs'), { recursive: true });
  // treeshakeCompensation keeps the (unused, side-effect-free) stylex
  // import in the transformed module — the fixture needs the package
  // resolvable exactly like a real app install would have it
  await symlink(join(packageRoot, 'node_modules'), join(fixtureRoot, 'node_modules'));
  await writeFile(
    join(fixtureRoot, 'src', 'kernel', 'tokens.stylex.ts'),
    [
      "import * as stylex from '@stylexjs/stylex';",
      '',
      "export const tokens = stylex.defineVars({",
      "  '--jx-probe': '#123456',",
      '});',
      '',
    ].join('\n'),
  );
  await writeFile(
    join(fixtureRoot, 'src', 'kernel', 'paint.ts'),
    [
      "import * as stylex from '@stylexjs/stylex';",
      "import { tokens } from './tokens.stylex';",
      '',
      'export const paint = stylex.create({',
      '  probe: {',
      "    color: tokens['--jx-probe'],",
      "    paddingInline: '16px',",
      '  },',
      '});',
      '',
      'export const probeClass = stylex.props(paint.probe).className;',
      '',
    ].join('\n'),
  );
  await writeFile(
    join(fixtureRoot, 'src', 'kernel', 'entry.ts'),
    [
      "import { probeClass } from './paint.ts';",
      ...(withCssEntry ? ["import './entry.css';"] : []),
      `console.log(probeClass); // keep the stylex module alive through tree-shaking`,
      '',
    ].join('\n'),
  );
  if (withCssEntry) {
    await writeFile(join(fixtureRoot, 'src', 'kernel', 'entry.css'), entryCss);
  }
}

async function findCssFiles(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await findCssFiles(p)));
    else if (p.endsWith('.css')) out.push(p);
  }
  return out;
}

// Gate-2 r3 P1: the merged asset carries EXACTLY ONE canonical
// statement (counted by the exact-bytes pattern, any tier count)
const countCanonicalStatements = (css: string): number =>
  (css.match(/@layer properties, theme, base, components(?:, components\.stylex\.priority[0-9]+)*, utilities;/g) ?? []).length;

describe('the stylex feature (build side, F11)', () => {
  it('canonicalLayerStatement pins the F9 canonical statement verbatim (dynamic tiers, utilities last)', () => {
    expect(canonicalLayerStatement(3)).toBe(F9_CANONICAL_N3);
    expect(canonicalLayerStatement(0)).toBe(F9_CANONICAL_SHEET);
    // monotone in N: every tier listed exactly once, utilities constant
    expect(canonicalLayerStatement(9).endsWith(', utilities;')).toBe(true);
    expect(canonicalLayerStatement(9)).toContain('components.stylex.priority9');
  });

  it('maxStylexPriority / parseCanonicalStatement round the law (statement must cover every carried tier)', () => {
    const css = `${canonicalLayerStatement(4)}\n@layer components.stylex.priority4 { .a { color: red; } }`;
    expect(maxStylexPriority(css)).toBe(4);
    expect(parseCanonicalStatement(css)?.maxPriority).toBe(4);
    // the escape shape: a top-level stylex tier block after a statement
    // that stopped early — parse still sees 3, max sees 4 (the gates
    // fail exactly this gap)
    const escape = `${canonicalLayerStatement(3)}\n@layer stylex.priority4 { .a { color: red; } }`;
    expect(maxStylexPriority(escape)).toBe(4);
    expect(parseCanonicalStatement(escape)?.maxPriority).toBe(3);
    // non-canonical openings are rejected
    expect(parseCanonicalStatement('@layer utilities;\n.x{}')).toBeNull();
    expect(parseCanonicalStatement('@layer properties, theme, base, components, utilities, stylex.priority1;\n')).toBeNull();
  });

  it('F9 layer law: the emitted css starts with the FULL statement at byte zero, engine output riding it', async () => {
    await writeKernelFixture(true);
    const outDir = join(outRoot, 'dist-with-entry');
    await build({
      root: fixtureRoot,
      logLevel: 'silent',
      plugins: jixoai({ ghostty: false, stylex: { include: ['src/kernel'] } }),
      build: {
        outDir,
        emptyOutDir: true,
        rollupOptions: { input: join(fixtureRoot, 'src', 'kernel', 'entry.ts') },
      },
    });

    const cssFiles = await findCssFiles(outDir);
    expect(cssFiles.length, 'exactly one css asset (the entry css, stylex appended)').toBe(1);
    const css = await readFile(cssFiles[0]!, 'utf8');
    // byte zero — the statement precedes EVERYTHING (Tailwind included)
    // and covers EVERY tier the css carries (the dynamic-N law)
    const expected = canonicalLayerStatement(maxStylexPriority(css));
    expect(css.startsWith(`${expected}\n`)).toBe(true);
    expect((parseCanonicalStatement(css)?.maxPriority ?? 0) >= maxStylexPriority(css)).toBe(true);
    // EXACTLY ONE canonical statement in the merged asset (Gate-2 r3)
    expect(countCanonicalStatements(css)).toBe(1);
    // the pre-existing entry css survived the bake (minifier-safe match)
    expect(css).toMatch(/margin:\s*0/);
    // the engine output really rode the asset: defineVars vars +
    // nested-tier atom rules (useCSSLayers prefix config)
    expect(css).toContain('--jx-probe:');
    expect(css).toContain('@layer components.stylex.priority1');
    expect(css).toContain('@layer components.stylex.priority2');
  });

  it('coverage-aware idempotence (Gate-2 r2 P1): a canonical(0) sheet entry is NOT a bake — atoms land in the linked asset, no unlinked fallback', async () => {
    // the legal folder-sheet opening (canonical(0), no stylex tiers) in
    // the entry css — the OLD code early-returned on "statement found"
    // and the atoms never reached the linked asset (writeBundle then
    // wrote an UNLINKED assets/stylex.css + warned)
    await writeKernelFixture(true, `${F9_CANONICAL_SHEET}\nbody { margin: 0; }\n`);
    const outDir = join(outRoot, 'dist-sheet-entry');
    await build({
      root: fixtureRoot,
      logLevel: 'silent',
      plugins: jixoai({ ghostty: false, stylex: { include: ['src/kernel'] } }),
      build: {
        outDir,
        emptyOutDir: true,
        rollupOptions: { input: join(fixtureRoot, 'src', 'kernel', 'entry.ts') },
      },
    });

    const cssFiles = await findCssFiles(outDir);
    // ONE css asset — the linked entry, baked; NO unlinked fallback
    expect(cssFiles.map((f) => f.slice(outDir.length))).not.toContain('/assets/stylex.css');
    expect(cssFiles.length).toBe(1);
    const css = await readFile(cssFiles[0]!, 'utf8');
    // the bake REPLACED the sheet statement with the full tier-covering
    // one at byte zero, and the atoms really rode the linked asset
    expect(css.startsWith(`${canonicalLayerStatement(maxStylexPriority(css))}\n`)).toBe(true);
    expect((parseCanonicalStatement(css)?.maxPriority ?? 0) >= maxStylexPriority(css)).toBe(true);
    expect(css).toContain('--jx-probe:');
    expect(css).toContain('@layer components.stylex.priority1');
    expect(css).toMatch(/margin:\s*0/);
    // EXACTLY ONE — the incoming sheet statement was STRIPPED, not kept
    expect(countCanonicalStatements(css)).toBe(1);
  });

  it('coverage-aware idempotence (Gate-2 r3): a tier-covering IMPORTED statement without the live atoms still bakes', async () => {
    // the includes() guard's negative case: an entry css opening with a
    // tier-covering canonical statement (the imported-payload shape)
    // whose atoms are NOT this build's — the live atoms must still be
    // baked in (skipping on coverage alone would drop them silently)
    await writeKernelFixture(true, `${canonicalLayerStatement(3)}\nbody { margin: 0; }\n`);
    const outDir = join(outRoot, 'dist-imported-statement');
    await build({
      root: fixtureRoot,
      logLevel: 'silent',
      plugins: jixoai({ ghostty: false, stylex: { include: ['src/kernel'] } }),
      build: {
        outDir,
        emptyOutDir: true,
        rollupOptions: { input: join(fixtureRoot, 'src', 'kernel', 'entry.ts') },
      },
    });
    const cssFiles = await findCssFiles(outDir);
    expect(cssFiles.length).toBe(1);
    const css = await readFile(cssFiles[0]!, 'utf8');
    expect(css).toContain('--jx-probe:'); // the LIVE atoms landed
    expect(countCanonicalStatements(css)).toBe(1); // and exactly one statement
  });

  it('coverage-aware idempotence (Gate-2 r2 P1): a COMPLETE previous bake is skipped — atoms appear exactly once, no fallback, no duplicate', async () => {
    // round 1: a normal bake; round 2: that OUTPUT is the entry css —
    // statement covers the tiers AND the collected atoms are already in
    // the asset, so the bake must skip (the pre-fix code instead dropped
    // cssInjected and wrote an unlinked duplicate fallback + warning).
    // Both rounds build UNMINIFIED: the includes() guard matches the
    // raw collected bytes (a MINIFIED prior bake re-bakes safely —
    // duplicate atom rules render identically; the guard errs toward
    // baking because a false positive drops atoms)
    const unminified = {
      root: fixtureRoot,
      logLevel: 'silent' as const,
      plugins: jixoai({ ghostty: false, stylex: { include: ['src/kernel'] } }),
      build: {
        minify: false,
        emptyOutDir: true,
        rollupOptions: { input: join(fixtureRoot, 'src', 'kernel', 'entry.ts') },
      },
    };
    await writeKernelFixture(true);
    const round1Dir = join(outRoot, 'dist-idem-r1');
    await build({ ...unminified, build: { ...unminified.build, outDir: round1Dir } });
    const r1Files = await findCssFiles(round1Dir);
    expect(r1Files.length).toBe(1);
    const baked = await readFile(r1Files[0]!, 'utf8');
    expect(baked).toContain('--jx-probe:');

    // round 2: the previous bake rides in as the entry css (the fixture
    // already exists from round 1 — only the entry css changes)
    await writeFile(join(fixtureRoot, 'src', 'kernel', 'entry.css'), baked);
    const round2Dir = join(outRoot, 'dist-idem-r2');
    await build({ ...unminified, build: { ...unminified.build, outDir: round2Dir } });
    const cssFiles = await findCssFiles(round2Dir);
    expect(cssFiles.map((f) => f.slice(round2Dir.length))).not.toContain('/assets/stylex.css');
    expect(cssFiles.length).toBe(1);
    const css = await readFile(cssFiles[0]!, 'utf8');
    // the skip held: the atom payload appears EXACTLY once (a re-bake
    // would append the collected css a second time)
    expect(css.match(/--jx-probe:/g)?.length).toBe(1);
    expect((css.match(/@layer components\.stylex\.priority1 \{/g) ?? []).length).toBe(1);
    expect(countCanonicalStatements(css)).toBe(1);
  });

  it('css-entry trap (§5.2): no css asset → fallback assets/stylex.css, statement-first, nothing silently lost', async () => {
    await writeKernelFixture(false);
    const outDir = join(outRoot, 'dist-no-entry');
    await build({
      root: fixtureRoot,
      logLevel: 'silent',
      plugins: jixoai({ ghostty: false, stylex: { include: ['src/kernel'] } }),
      build: {
        outDir,
        emptyOutDir: true,
        rollupOptions: { input: join(fixtureRoot, 'src', 'kernel', 'entry.ts') },
      },
    });

    const cssFiles = await findCssFiles(outDir);
    expect(cssFiles.map((f) => f.slice(outDir.length))).toEqual(['/assets/stylex.css']);
    const css = await readFile(cssFiles[0]!, 'utf8');
    expect(css.startsWith(`${canonicalLayerStatement(maxStylexPriority(css))}\n`)).toBe(true);
    expect(css).toContain('@layer components.stylex.priority1');
  });

  it('kernel-scope gate: out-of-scope ids never reach the transform; in-scope ids do', async () => {
    const engine = createStylexEngine(
      { include: [join(fixtureRoot, 'src', 'kernel')] },
      { root: fixtureRoot, command: 'build' },
    );
    const codeWithStylexImport = "import * as stylex from '@stylexjs/stylex';\nexport const x = stylex.create({ a: { color: 'red' } });\n";

    // docs-route shape: outside the kernel trees → null BEFORE the engine
    expect(await engine.transform(codeWithStylexImport, join(fixtureRoot, 'src', 'docs', 'page.ts'))).toBeNull();
    // node_modules shape → null
    expect(
      await engine.transform(codeWithStylexImport, join(fixtureRoot, 'node_modules', 'dep', 'mod.js')),
    ).toBeNull();
    // query-suffixed kernel ids still scope-match ('?svelte' HMR shape)
    expect(await engine.transform(codeWithStylexImport, join(fixtureRoot, 'src', 'kernel', 'comp.svelte?v=1'))).not.toBeNull();
    // in-scope plain module → transformed: stylex.create compiled to
    // the class-constant table (treeshakeCompensation legitimately
    // KEEPS the unused side-effect-free import — that is not a leak,
    // the bundler drops it; the compiled table is the proof)
    const transformed = (await engine.transform(codeWithStylexImport, join(fixtureRoot, 'src', 'kernel', 'paint.ts'))) as {
      code: string;
    };
    expect(transformed.code).not.toContain('stylex.create');
    expect(transformed.code).toMatch(/\$\$css:/);
  });

  it('empty include is the named startup error (the scope is the law)', () => {
    expect(() => jixoai({ ghostty: false, stylex: { include: [] } })).toThrowError(/non-empty include/);
  });
});
