// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/prose
// buildId: 7d8bb67bcc5beef8859cf82b33c794060d8194b509264c6570ab4ab974ef5ae3
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const proseStyles = Object.freeze({
  "host": "xc68ue2 x1dbl2gt",
  "familyMono": "x1mwizrc",
  "familySerif": "xv4si4x",
  "inkMuted": "xowzrx4",
  "inkPrimary": "x18as732",
  "inkDestructive": "xb7qa0x",
  "groundBackground": "x1rnfs7p",
  "groundCard": "x13udha1",
  "groundPopover": "xfmjrly",
  "groundMuted": "x1yn5p49",
  "groundSecondary": "x1yill5n",
  "groundAccent": "xn7yb31",
  "groundTransparent": "xjbqb8w",
  "alignCenter": "x2b8uid",
  "alignEnd": "xp4054r",
  "alignJustify": "xmw9mke",
  "wrapPretty": "x1fzhlzt",
  "wrapBalance": "x1w2vvpw",
  "wrapStable": "x1yjdo0r",
  "hyphensAuto": "xkjl1po",
  "hyphensNone": "xuix1fa",
  "hyphensManual": "xxydokm",
});
