// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/demo
// buildId: 0ce7cb9fd93bfb6d0c326c10126a270111182c0d8894fc9ce51d327ff7ca2ee0
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const demo = Object.freeze({
  "page": "x1uedy8c x19bbpc0 x78zum5 xdt5ytf x1c1vhfx",
  "title": "x1jvydc1 x1s688f x1ghz6dp",
  "note": "x1qt5hsa x1dbl2gt xowzrx4 x1ghz6dp",
  "section": "x78zum5 xdt5ytf x1v2ro7d x1tamke2 xmkeg23 x1y0btm7 xwi7vqo x13udha1",
  "sectionTitle": "x1j6dyjg x9pfba7 xtvhhri xowzrx4 x1ghz6dp",
  "row": "x78zum5 x6s0dn4 x1v2ro7d x1a02dak",
  "ground": "xl2d5wq x1tamke2 x78zum5 xdt5ytf x1v2ro7d",
  "nav": "x78zum5 x167g77z x1a02dak x6s0dn4 xsag5q8 xso031l x1q0q8m5 x1g6nami",
  "navLink": "xfifm61 xl8unsv x1hl2dhg x1dumkz1",
  "toggleRow": "x8x9d4c x78zum5 x167g77z x6s0dn4 xfifm61",
  "miniButton": "x1j6dyjg xmfpazt x1ypdohk x1yn5p49 xl8unsv xmkeg23 x1y0btm7 xwi7vqo",
});
