// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: toggle-group
// buildId: f6558fb12906568c70cc330f4e3cb1a3cd4765df5da5bf5a7ace526ad3b96eed
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const toggleGroupStyles = Object.freeze({
  "content": "x3nfvp2 x6s0dn4 x1xsfxl3",
  "slotStart": "x3nfvp2",
  "slotEnd": "x3nfvp2",
});
