// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: toggle-group
// buildId: 654954299e69627125bd42b76c4c97064da9f26b80ed6b67cbb2832feb1baf07
// generator: @jixoai/ui-vite-plugin@0.6.0
// engine: @stylexjs/unplugin@0.19.0
export const toggleGroupStyles = Object.freeze({
  "content": "x3nfvp2 x6s0dn4 x1xsfxl3",
  "slotStart": "x3nfvp2",
  "slotEnd": "x3nfvp2",
});
