// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: toggle-group
// buildId: b3ad961302de84899611d87ca5d0c5c564f205140fe2b2a2409e6feb8bf37b44
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const toggleGroupStyles = Object.freeze({
  "content": "x3nfvp2 x6s0dn4 x1xsfxl3",
  "slotStart": "x3nfvp2",
  "slotEnd": "x3nfvp2",
});
