// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: scroll-run
// buildId: fa64ecad5239b9c22987268e54d1df02526b078881da49e0c55932e51dfdb0e9
// generator: @jixoai/ui-vite-plugin@0.6.0
// engine: @stylexjs/unplugin@0.19.0
export const scrollChromeStyles = Object.freeze({
  "veilLayer": "xrvj5dj x15r89dc x47corl",
  "shadowVeil": "x15r89dc x17dzmu4",
});
