// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: scroll-run
// buildId: e12c98c6feb373f1861e907a966420d7969018bd07cbc08ac11a31858f99eeac
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const scrollChromeStyles = Object.freeze({
  "veilLayer": "xrvj5dj x15r89dc x47corl",
  "shadowVeil": "x15r89dc x17dzmu4",
});
