// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/press-button
// buildId: 077eddbfa23601ef938bc175cf6f5893ed839e10ecf9696098b5a115debeaa34
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const pressButtonStyles = Object.freeze({
  "base": "x3nfvp2 x1bhj078 x6s0dn4 xc68ue2 xxguibh xn212u0 xk50ysn x9f619 xzgn1n2 xnroaok x153txnh xxingfx x1unuef7 x1xtu34k x7s97pk x9kvfbb",
  "textBody": "xiouwu1 xwwigjq",
  "squareBody": "xu9qwbo xl56j7k",
  "frame": "xmkeg23 x1y0btm7",
  "fill": "x1kkbjiu x1v5t2t x2jy0tw xnwy5bs x1ylmb6m x1ggml12",
  "tonal": "x10pxzsq xujm0qo x17xghzz x9yvj25 x1w1tqly xs5hli",
  "outline": "xjbqb8w x1m622hh xl8unsv x1n5puvy x9yvj25 x1w1tqly xs5hli",
  "ghost": "xjbqb8w x9r1u3d xl8unsv x1n5puvy xytmldf x1qbsd4u x16rn130 xs5hli x1tvaz0g xme02mz",
  "link": "x18as732 xkrqix3 x1kuah0p x3pynha x1sur9pj x1ljrylj",
  "flatActiveTint": "x9jfcoq x1yqlv2b x117h8l x1oyek6m x18y30we x198b5v xcshi6i x1xzl2b1 x1xqyx04 xhv4qot xtbvb47 x3t03n0 xrjd2uv",
  "flatHost": "x1n2onr6",
  "spinnerWrap": "x3nfvp2 x6s0dn4 x1mwizrc x18as732",
  "spinnerFrames": "x1n2onr6 xwz0xwf xayc3bl x2b8uid x3ajldb",
  "spinnerFrame": "x1j61x8r x1agbcgv xcrlgei x1ief7js xemfg65 x1nxgg22 xa4qsjk x1aquc0h",
  "frameVisible": "xnpuxes",
  "frameHidden": "xlshs6z",
  "delay200": "x1t83zlg",
  "delay400": "x1xwhvez",
  "delay600": "x1nrwgbl",
  "checkGlyph": "x3nfvp2 x1okw0bk x6s0dn4 x18as732",
});
