// Ambient types for the `virtual:jixoai-ghostty` module generated by
// @jixoai/vite-plugin at build/dev time. Named exports only — the module
// shape matches src/index.ts exactly (no default in the type surface).
//
// Consumer wiring (one line in a project d.ts environment file):
//   /// <reference types="@jixoai/vite-plugin/client" />

declare module 'virtual:jixoai-ghostty' {
  export const url: string;
  export const sha256: string;
  export const variant: 'full' | 'small';
  export const buildInfo: string;
}
