// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/search-palette
// buildId: 0ce7cb9fd93bfb6d0c326c10126a270111182c0d8894fc9ce51d327ff7ca2ee0
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const searchPaletteStyles = Object.freeze({
  "contents": "xjp7ctv",
  "dialog": "x1ae7lm2 x1ent6eq xkqzi3r",
  "headerCol": "xcrlgei",
  "inputFlex": "xh8yej3 xeuugli x845mor",
  "searchIcon": "x1okw0bk x87ps6o xowzrx4",
  "flightGap": "x78zum5 x1okw0bk x1oz3d4u",
  "flightRow": "x78zum5 x1oz3d4u",
  "pending": "x78zum5 x6s0dn4 x1kupzwg x1vdvkue xd6yja7",
  "pendingText": "x1mwizrc xgriabn xowzrx4",
  "empty": "x78zum5 xdt5ytf x6s0dn4 xbybx4j x1vdvkue x6lyrv3 x2b8uid",
  "emptyIcon": "x87ps6o x1tmf4wr",
  "emptyTitle": "x1mwizrc xwt6n1l x1k3bwac",
  "emptyTitleInk": "xl8unsv",
  "emptyHint": "x6yizsu x1eo1nwe",
  "list": "xuv47z4",
  "option": "x1lliihq x4vrqqa xy01hyd xiys7bm",
  "optionActive": "xgj90kv",
  "optionPage": "x1mwizrc x1o1qgpq xtvhhri x67e80a x1eo1nwe",
  "optionHeading": "xuiqbm1 x1mwizrc xxguibh xo3t9el",
  "optionSummary": "xuiqbm1 x104kibb x1h7i4cw x1ua5tub xb3r6kr xgriabn x1fhg5ek xowzrx4",
  "summaryMark": "xjbqb8w x18as732",
});
