/**
 * llms-txt generator end-to-end tests (test/llms-txt.spec.ts).
 *
 * Runs generateLlmsTxt against temp-dir fixtures shaped like a real static
 * dist: index composition, per-page .md mirrors + provenance markers,
 * exclusion/noindex, byte-determinism (idempotent re-runs), hand-written
 * .md conflicts, the llms-full.txt size cap, per-locale index splitting,
 * additional entries, link styles, and site URLs that carry a base path.
 */
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { generateLlmsTxt, llmsTxt } from '../../../registry/files/llms-txt/llms-txt.mjs';

const isDirectorySync = (file: string) => statSync(file).isDirectory();

const page = (options: { h1: string; desc: string; body?: string; noindex?: boolean }) =>
  `<!doctype html><html><head><title>${options.h1} · site</title>` +
  `<meta name="description" content="${options.desc}"/>` +
  (options.noindex ? '<meta name="robots" content="noindex"/>' : '') +
  `</head><body><header>site header</header><main><h1>${options.h1}</h1>` +
  `<p>${options.body ?? `${options.h1} body text.`}</p></main><script>hydration()</script></body></html>`;

function makeDist(files: Record<string, string>) {
  const dir = mkdtempSync(path.join(tmpdir(), 'llms-txt-'));
  for (const [rel, content] of Object.entries(files)) {
    const file = path.join(dir, ...rel.split('/'));
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, content, 'utf8');
  }
  return dir;
}

const dirs: string[] = [];
afterEach(() => {
  while (dirs.length) rmSync(dirs.pop()!, { recursive: true, force: true });
});

const baseConfig = {
  siteUrl: 'https://site.jixoai.com',
  title: 'site',
  summary: 'A fixture site.',
};

const standardDist = () =>
  makeDist({
    'index.html': page({ h1: 'Home', desc: 'The home page.' }),
    'docs/install.html': page({ h1: 'Install', desc: 'How to install.', body: 'Install body.' }),
    'internal.html': page({ h1: 'Internal', desc: 'noindex', noindex: true }),
    '404.html': page({ h1: 'Not found', desc: 'missing' }),
    '_app/immutable/chunk.js': '// not html, never scanned',
  });

describe('generateLlmsTxt end to end', () => {
  it('composes the index: H1, blockquote, sections, absolute .md links, descriptions', () => {
    const dir = standardDist();
    dirs.push(dir);
    const report = generateLlmsTxt(dir, baseConfig);
    const index = readFileSync(path.join(dir, 'llms.txt'), 'utf8');

    expect(index).toContain('# site\n\n> A fixture site.\n');
    expect(index).toContain('## Docs\n');
    expect(index).toContain(
      '- [Install](https://site.jixoai.com/docs/install.md): How to install.',
    );
    expect(index).toContain('- [Home](https://site.jixoai.com/index.md): The home page.');
    expect(report.pages).toBe(2); // noindex + 404 never counted
    expect(report.skipped).toEqual(['internal.html']);
  });

  it('writes per-page .md mirrors with provenance markers; excluded pages get none', () => {
    const dir = standardDist();
    dirs.push(dir);
    generateLlmsTxt(dir, baseConfig);

    const install = readFileSync(path.join(dir, 'docs', 'install.md'), 'utf8');
    expect(install).toContain(
      '<!-- generated by jixoai llms-txt · do not edit · source: https://site.jixoai.com/docs/install -->',
    );
    expect(install).toContain('# Install\n\nInstall body.\n');

    const home = readFileSync(path.join(dir, 'index.md'), 'utf8');
    expect(home).toContain('source: https://site.jixoai.com/ -->');

    expect(readFileSync(path.join(dir, 'internal.html'), 'utf8')).toBeTruthy();
    expect(() => readFileSync(path.join(dir, 'internal.md'))).toThrow();
    expect(() => readFileSync(path.join(dir, '404.md'))).toThrow();
  });

  it('is byte-deterministic across re-runs (idempotent convergence)', () => {
    const dir = standardDist();
    dirs.push(dir);
    const first = generateLlmsTxt(dir, baseConfig);
    const snapshot = first.files.map((file) => [file.path, file.bytes] as const);
    const second = generateLlmsTxt(dir, baseConfig);
    expect(second.files.map((file) => [file.path, file.bytes] as const)).toEqual(snapshot);
    expect(second.files.find((f) => f.path === 'llms.txt')?.bytes).toBe(
      first.files.find((f) => f.path === 'llms.txt')?.bytes,
    );
  });

  it('refuses to overwrite hand-written .md at a target path', () => {
    const dir = standardDist();
    dirs.push(dir);
    writeFileSync(path.join(dir, 'docs', 'install.md'), '# hand-written\n', 'utf8');
    expect(() => generateLlmsTxt(dir, baseConfig)).toThrow(
      /refusing to touch conflicting outputs: docs\/install\.md \(hand-written markdown\)/,
    );
    expect(readFileSync(path.join(dir, 'docs', 'install.md'), 'utf8')).toBe('# hand-written\n');
  });

  it('rejects duplicate page/mirror targets before writing anything', () => {
    // only a config that scans both suffixes can produce the collision —
    // a.html and a.htm both mirror to a.md
    const dir = makeDist({
      'a.html': page({ h1: 'A', desc: 'first' }),
      'a.htm': page({ h1: 'A2', desc: 'same mirror path' }),
    });
    dirs.push(dir);
    expect(() =>
      generateLlmsTxt(dir, { ...baseConfig, include: ['**/*.htm', '**/*.html'] }),
    ).toThrow(/duplicate page\/mirror targets/);
    expect(existsSync(path.join(dir, 'llms.txt'))).toBe(false);
    expect(existsSync(path.join(dir, 'a.md'))).toBe(false);
  });

  it('aborts untouched when a directory occupies a declared output path', () => {
    const dir = standardDist();
    dirs.push(dir);
    // a prior successful run leaves generated outputs; a directory later
    // squatting on llms.txt must abort the rerun with zero mutations
    generateLlmsTxt(dir, baseConfig);
    const mirrorBefore = readFileSync(path.join(dir, 'index.md'), 'utf8');
    rmSync(path.join(dir, 'llms.txt'));
    mkdirSync(path.join(dir, 'llms.txt'));
    expect(() => generateLlmsTxt(dir, baseConfig)).toThrow(/directory occupies the output path/);
    expect(isDirectorySync(path.join(dir, 'llms.txt'))).toBe(true); // untouched
    expect(readFileSync(path.join(dir, 'index.md'), 'utf8')).toBe(mirrorBefore);
    expect(readdirSync(dir).filter((entry) => entry.startsWith('.llms-txt-staging'))).toEqual([]);
  });

  it('rejects dangerous additionalEntries urls before writing anything', () => {
    const dir = standardDist();
    dirs.push(dir);
    expect(() =>
      generateLlmsTxt(dir, {
        ...baseConfig,
        additionalEntries: [{ name: 'bad', url: 'javascript:alert(1)' }],
      }),
    ).toThrow(/additionalEntries url must be absolute http\(s\)\/mailto or root-relative/);
    expect(existsSync(path.join(dir, 'llms.txt'))).toBe(false);
  });

  it('skips llms-full.txt entirely when full.enabled is false', () => {
    const dir = standardDist();
    dirs.push(dir);
    generateLlmsTxt(dir, { ...baseConfig, full: { enabled: false } });
    expect(existsSync(path.join(dir, 'llms.txt'))).toBe(true);
    expect(existsSync(path.join(dir, 'llms-full.txt'))).toBe(false);
  });

  it('links directory index mirrors at their real path (docs/index.html → docs/index.md)', () => {
    const dir = makeDist({
      'index.html': page({ h1: 'Home', desc: 'root' }),
      'docs/index.html': page({ h1: 'Docs', desc: 'section index' }),
    });
    dirs.push(dir);
    generateLlmsTxt(dir, baseConfig);
    const index = readFileSync(path.join(dir, 'llms.txt'), 'utf8');
    expect(index).toContain('[Home](https://site.jixoai.com/index.md)');
    expect(index).toContain('[Docs](https://site.jixoai.com/docs/index.md)');
    expect(index).not.toContain('/docs/.md');
    // every index .md link resolves to a file on disk
    for (const match of index.matchAll(/\]\((https:\/\/site\.jixoai\.com\/[^)]+\.md)\)/g)) {
      const rel = match[1].slice('https://site.jixoai.com/'.length);
      expect(existsSync(path.join(dir, ...rel.split('/'))), rel).toBe(true);
    }
  });

  it('fails loudly when llms-full.txt exceeds the size cap (no silent truncation)', () => {
    const dir = standardDist();
    dirs.push(dir);
    expect(() =>
      generateLlmsTxt(dir, { ...baseConfig, full: { enabled: true, maxBytes: 10 } }),
    ).toThrow(/over the 10B cap/);
  });

  it('supports root-relative links and disabling per-page mirrors', () => {
    const dir = standardDist();
    dirs.push(dir);
    generateLlmsTxt(dir, { ...baseConfig, linkStyle: 'root-relative' as const, perPageMarkdown: false });
    const index = readFileSync(path.join(dir, 'llms.txt'), 'utf8');
    expect(index).toContain('[Install](/docs/install.md)');
    expect(() => readFileSync(path.join(dir, 'docs', 'install.md'))).toThrow();
  });

  it('joins siteUrl base paths correctly (github pages style)', () => {
    const dir = standardDist();
    dirs.push(dir);
    generateLlmsTxt(dir, { ...baseConfig, siteUrl: 'https://user.github.io/repo/' });
    const index = readFileSync(path.join(dir, 'llms.txt'), 'utf8');
    expect(index).toContain('[Install](https://user.github.io/repo/docs/install.md)');
  });

  it('assigns sections by first match, with a Pages fallback for the rest', () => {
    const dir = standardDist();
    dirs.push(dir);
    generateLlmsTxt(dir, {
      ...baseConfig,
      sections: [{ title: 'Getting started', include: ['index.html'] }],
    });
    const index = readFileSync(path.join(dir, 'llms.txt'), 'utf8');
    expect(index.indexOf('## Getting started')).toBeGreaterThan(-1);
    expect(index).toContain('## Pages\n');
    expect(index.indexOf('## Getting started')).toBeLessThan(index.indexOf('## Pages'));
  });

  it('appends additional entries under Optional with absolute urls', () => {
    const dir = standardDist();
    dirs.push(dir);
    generateLlmsTxt(dir, {
      ...baseConfig,
      additionalEntries: [
        {
          optional: true,
          name: 'Registry index',
          url: '/r/registry.json',
          description: 'The machine-readable index.',
        },
      ],
    });
    const index = readFileSync(path.join(dir, 'llms.txt'), 'utf8');
    expect(index).toContain(
      '- [Registry index](https://site.jixoai.com/r/registry.json): The machine-readable index.',
    );
    expect(index).toContain('## Optional');
  });

  it('uses off-site http(s)/mailto additional entry urls verbatim (never joined)', () => {
    const dir = standardDist();
    dirs.push(dir);
    generateLlmsTxt(dir, {
      ...baseConfig,
      additionalEntries: [
        { name: 'Ext', url: 'https://other.test/x' },
        { name: 'Contact', url: 'mailto:owner@example.com' },
      ],
    });
    const index = readFileSync(path.join(dir, 'llms.txt'), 'utf8');
    expect(index).toContain('[Ext](https://other.test/x)');
    expect(index).toContain('[Contact](mailto:owner@example.com)');
    expect(index).not.toContain('site.jixoai.comhttps://');
    expect(index).not.toContain('site.jixoai.commailto:');
  });

  it('llms-full.txt = index first, then url-headed page bodies', () => {
    const dir = standardDist();
    dirs.push(dir);
    generateLlmsTxt(dir, baseConfig);
    const full = readFileSync(path.join(dir, 'llms-full.txt'), 'utf8');
    expect(full.startsWith('# site\n')).toBe(true);
    expect(full).toContain('\n---\n\n# Home\n\nhttps://site.jixoai.com/\n');
    expect(full).toContain('# Install\n\nhttps://site.jixoai.com/docs/install\n');
    expect(full).not.toContain('Internal body');
  });
});

describe('locale splitting', () => {
  const localeDist = () =>
    makeDist({
      'index.html': page({ h1: 'Home', desc: 'shared landing' }),
      'en/guide.html': page({ h1: 'Guide EN', desc: 'english guide' }),
      'zh/guide.html': page({ h1: '指南', desc: '中文指南' }),
    });

  it('writes per-locale indexes and a default-locale root index', () => {
    const dir = localeDist();
    dirs.push(dir);
    generateLlmsTxt(dir, {
      ...baseConfig,
      locale: { segments: ['en', 'zh'], default: 'en' },
    });

    const en = readFileSync(path.join(dir, 'en', 'llms.txt'), 'utf8');
    expect(en).toContain('[Guide EN](https://site.jixoai.com/en/guide.md)');
    expect(en).not.toContain('zh/guide');

    const zh = readFileSync(path.join(dir, 'zh', 'llms.txt'), 'utf8');
    expect(zh).toContain('[指南](https://site.jixoai.com/zh/guide.md)');
    expect(zh).not.toContain('en/guide');

    const root = readFileSync(path.join(dir, 'llms.txt'), 'utf8');
    expect(root).toContain('[Guide EN](https://site.jixoai.com/en/guide.md)');
    expect(root).toContain('## Other languages');
    expect(root).toContain('[llms.txt (zh)](https://site.jixoai.com/zh/llms.txt)');

    // every locale still gets its per-page .md mirrors…
    expect(readFileSync(path.join(dir, 'zh', 'guide.md'), 'utf8')).toContain('# 指南');
    // …but llms-full.txt follows the default locale only
    const full = readFileSync(path.join(dir, 'llms-full.txt'), 'utf8');
    expect(full).toContain('Guide EN');
    expect(full).not.toContain('# 指南');
  });

  it('writes an index for a configured segment with no pages of its own', () => {
    const dir = makeDist({ 'en/guide.html': page({ h1: 'Guide EN', desc: 'english' }) });
    dirs.push(dir);
    generateLlmsTxt(dir, { ...baseConfig, locale: { segments: ['en', 'zh'], default: 'en' } });
    const zh = readFileSync(path.join(dir, 'zh', 'llms.txt'), 'utf8');
    expect(zh).toContain('# site\n\n> A fixture site.');
    const root = readFileSync(path.join(dir, 'llms.txt'), 'utf8');
    expect(root).toContain('[llms.txt (zh)](https://site.jixoai.com/zh/llms.txt)');
  });

  it('rolls back the whole commit when a mid-commit rename fails (test seam)', () => {
    const dir = makeDist({ 'en/guide.html': page({ h1: 'Guide EN', desc: 'english guide' }) });
    dirs.push(dir);
    const locale = { segments: ['en', 'zh'], default: 'en' as const };
    // outputs commit in order: en/llms.txt, zh/llms.txt, llms.txt, …
    // fail at index 2 → the first two (including the NEW zh/ directory)
    // must vanish again, leaving the dist byte-identical to before.
    expect(() =>
      generateLlmsTxt(dir, {
        ...baseConfig,
        locale,
        __testFailCommitAfter: 1,
      } as never),
    ).toThrow(/commit failed and was rolled back: injected commit failure/);
    expect(existsSync(path.join(dir, 'en', 'llms.txt'))).toBe(false);
    expect(existsSync(path.join(dir, 'zh'))).toBe(false);
    expect(existsSync(path.join(dir, 'llms.txt'))).toBe(false);
    expect(existsSync(path.join(dir, 'llms-full.txt'))).toBe(false);
    expect(readdirSync(dir).filter((entry) => entry.startsWith('.llms-txt-staging'))).toEqual([]);
  });
});

describe('guards', () => {
  it('rejects a non-absolute siteUrl with a clear message', () => {
    const dir = standardDist();
    dirs.push(dir);
    expect(() => generateLlmsTxt(dir, { ...baseConfig, siteUrl: 'site.jixoai.com' })).toThrow(
      /config\.siteUrl must be an absolute URL/,
    );
  });

  it('rejects a missing dist directory', () => {
    expect(() => generateLlmsTxt('/nonexistent-llms-txt-dist', baseConfig)).toThrow(
      /dist directory does not exist/,
    );
  });
});

describe('vite plugin adapter', () => {
  it('exposes a post-enforced plugin that skips non-SSR and dev contexts', () => {
    const plugin = llmsTxt({ ...baseConfig, distDir: 'dist' });
    expect(plugin.name).toBe('jixoai:llms-txt');
    expect(plugin.enforce).toBe('post');
    // no resolved config (dev-like) → closeBundle is a no-op, never throws
    plugin.closeBundle();
    const resolved = { command: 'build', build: { ssr: false }, root: process.cwd() };
    plugin.configResolved(resolved);
    plugin.closeBundle(); // client build → skipped
  });
});
