// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/code-card
// buildId: b3ad961302de84899611d87ca5d0c5c564f205140fe2b2a2409e6feb8bf37b44
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const codeCardStyles = Object.freeze({
  "card": "x1ghz6dp xeuugli x10g96x4 xmkeg23 x1y0btm7 x3qsdy5 x78zum5 xdt5ytf xbjcvb9",
  "cardFill": "x5yr21d",
  "head": "x78zum5 x6s0dn4 x8233eu xeuugli x1ryrjj2 x1f1z27m x1j6dyjg x9pfba7 xpzske6 xso031l x1q0q8m5 xb2d4eo x1ym7tfx",
  "file": "xzavzzj xb3r6kr xlyipyv xuxw1ft",
  "side": "x78zum5 x6s0dn4 x8x9d4c xeuugli",
  "lang": "x1labic3 x18km98s xtvhhri xuxw1ft",
  "scrollWrap": "x1n2onr6 xeuugli",
  "scrollWrapFill": "x78zum5 x98rzlu x2lwn1j xdt5ytf",
  "pre": "x1ghz6dp x1mwizrc x1ct8sxb x1dbl2gt x1fwvsoz xw2csxc xryxfnj x7p5m3t xliy32w x142x9wm x7hf3t x1k5ss6i x14b2esq x1bqaal x1hhue18",
  "vscroll": "x1odjw0f",
  "preFill": "x98rzlu x2lwn1j x1odjw0f",
  "veilStart": "x10tli2e x1hmns74 x1nc033x x1682cnc x12s5fzi xkk1bqk x124lp2h x1de4urk x13o46a3 xy5ulmt xxlzmds xp6epc3 xdr5qw3 x12udz3x x1w1d2iz",
  "veilEnd": "x100rkj9 x1j6awrg xd54j2p x1unh1gc xsfccug x2q1x1w xmf22ne x1hbq0ec x7l6x83 x11yo84x x12ip6w2 x3sh4h5 x13rawyw xtveyhk x15k16ov",
  "veilStartOn": "xfbg1o9",
  "veilEndOn": "x1rw2j67",
  "veilReducedMotion": "x13sdc92 x4oqjru",
  "foot": "x78zum5 x6s0dn4 x1qughib x8233eu x1a5yqsw x30hkwx xe0cj4x x1m83qfk xqfkjy8 x178xt8z x13fuv20 x7n9ejg",
  "footSide": "x78zum5 x6s0dn4 xeuugli",
});
