// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: native-scroll-area
// buildId: 0ce7cb9fd93bfb6d0c326c10126a270111182c0d8894fc9ce51d327ff7ca2ee0
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const nativeScrollAreaStyles = Object.freeze({
  "area": "x1n2onr6",
  "vertical": "x6ikm8r x1odjw0f",
  "horizontal": "xw2csxc x10wlt62",
  "both": "xw2csxc x1odjw0f",
  "content": "x5yr21d",
});
