// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: native-scroll-area
// buildId: f6558fb12906568c70cc330f4e3cb1a3cd4765df5da5bf5a7ace526ad3b96eed
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const nativeScrollAreaStyles = Object.freeze({
  "area": "x1n2onr6",
  "vertical": "x6ikm8r x1odjw0f",
  "horizontal": "xw2csxc x10wlt62",
  "both": "xw2csxc x1odjw0f",
  "content": "x5yr21d",
});
