// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/docs-sections-nav
// buildId: fa64ecad5239b9c22987268e54d1df02526b078881da49e0c55932e51dfdb0e9
// generator: @jixoai/ui-vite-plugin@0.6.0
// engine: @stylexjs/unplugin@0.19.0
export const dsnStyles = Object.freeze({
  "bandZ": "x1u8a7rm",
});
