// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/switch
// buildId: 077eddbfa23601ef938bc175cf6f5893ed839e10ecf9696098b5a115debeaa34
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const switchStyles = Object.freeze({
  "label": "xxguibh xn212u0 xl8unsv",
  "track": "xjyslct x1lugfcp x9f619 x1n2onr6 x62ywxn xo805f9 x1ghz6dp x1okw0bk x1w89k0k xc342km xng3xce xbgdi8x xtkphhm x1yn5p49 x1ypdohk x6y0dih x18yi6u2 xg9knx0 x14acvgp xy9f4xx xijokvz x1s07b3s",
  "knob": "x10tli2e x1hmns74 xtql2tq x1qzzs4r x1yyf8ht x10kowwv x101mhmm x1ql9qlr xz8fyzm x1fo1fc9 x4ku27x xd5hkx5 x1458kei x1v6rcj3 xsnaal3 x1dtxr84 x9kvfbb x1fgujza",
});
