// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: progressive-blur
// buildId: 0ce7cb9fd93bfb6d0c326c10126a270111182c0d8894fc9ce51d327ff7ca2ee0
// generator: @jixoai/ui-vite-plugin@0.5.1
// engine: @stylexjs/unplugin@0.19.0
export const pblurStyles = Object.freeze({
  "scenery": "x47corl",
  "gridBand": "xrvj5dj x17dzmu4",
  "gridStart": "x15r89dc x1lqcxt8 xkh2ocl",
  "gridEnd": "x15r89dc x1qab1bc xkh2ocl",
  "gridTop": "x19bwqal x1osaytk x1y8v6su",
  "gridBottom": "x19bwqal x1osaytk x7fd4wk",
  "gridLayer": "x15r89dc",
  "stickyRoot": "x7wzq59 x1n327nk",
  "hZero": "xqtp20y",
  "wZero": "xnalus7",
  "topEdge": "x13vifvy",
  "bottomEdge": "x1ey2m1c",
  "startEdge": "x1o0tod",
  "endEdge": "xtijo5x",
  "bandBlock": "x10l6tqk x17y0mx6",
  "bandInline": "x10l6tqk x10no89f",
  "layer": "x10l6tqk x10a8y8t",
});
