// vite.config.ts — d3/arch-c: precompiled css + class constants
// (channel-collapse §3 column C). NO transform wiring at all: the
// kernel ships compiled artifacts (src/**\/ *.stylex.js — the babel
// output of the .stylex.ts sources — + src/kernel-precompiled/
// stylex.css). The consumer's entire wiring is the ONE css import in
// src/main.ts; @stylexjs/stylex stays a RUNTIME dependency (styleq
// for attrs()/dynamic merging). Generated by spike/d3/precompile
// (kernel-build side, NOT in this consumer's closure).
import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';

export default defineConfig({
  plugins: [svelte()],
});
