// @generated by scripts/gen-stylex-payload.mjs — DO NOT EDIT.
// verify:stylex-payload re-derives these bytes; a hand edit fails the gate naming the artifact + mismatch.
// item: corpus/range
// buildId: 60807e498baf091b1e47652e09051c40fe6817a687a7e2b1e63402a96062740f
// generator: @jixoai/ui-vite-plugin@0.3.0
// engine: @stylexjs/unplugin@0.19.0
export const rangeStyles = Object.freeze({
  "field": "x78zum5 xdt5ytf x195vfkc",
  "fieldVertical": "x1q0g3np x1qjc9v5 xpj7pl4",
  "head": "x78zum5 x1pha0wt x1qughib x8233eu",
  "label": "xxguibh xn212u0 xl8unsv",
  "srOnly": "x10l6tqk x1i1rx1s xjm9jq1 x1717udv xkdpibf xb3r6kr xeh89do xuxw1ft xc342km xng3xce",
  "readout": "xxguibh xn212u0 x1mwizrc xss6m8b xl8unsv",
  "readoutInvalid": "xb7qa0x",
  "bodyHorizontal": "x1lliihq",
  "bodyVertical": "x78zum5 x1qjc9v5 xpj7pl4",
  "rulerHorizontal": "x1n2onr6 x16wp3ig x72edsj x1sz5sl3",
  "rulerVertical": "x1n2onr6 x1jw3ynk xt7dq6l xkh2ocl x1jneikf xrxpjvj",
  "endTickH": "x100rkj9 x1j6awrg x1unh1gc x1m1drc7 x1xrz1ek xv6d0c5 xm4hkmz",
  "endTickV": "x100rkj9 x1i63x89 x1xrz1ek x17cx49 xnbfe2x x183bm9d xcock1l x1j6awrg xm4hkmz",
  "tickH": "x10l6tqk x17y0mx6 x13vifvy x5yr21d x1mbdtfs x4gfg63",
  "tickV": "x10l6tqk x10no89f x80663w x1o0tod xh8yej3 xt7dq6l xx27f0d",
  "error": "x1ghz6dp xxguibh xn212u0 xb7qa0x",
  "errorMark": "x1j61x8r x1xlr1w8 xgpuomr",
});
